# Pre-commit configuration for PyRISE
# Run `pre-commit install` to set up git hooks
# Run `pre-commit run --all-files` to check all files

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]  # Allow custom YAML tags in model files
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --line-length=88]

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          --max-line-length=88,
          --extend-ignore=E203,W503,  # Ignore Black-compatible issues
          --max-complexity=10,
          --select=E,W,F,C,N,
          --per-file-ignores=__init__.py:F401  # Allow unused imports in __init__.py
        ]
        additional_dependencies:
          - flake8-docstrings
          - flake8-comprehensions
          - flake8-bugbear

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --strict]
        additional_dependencies:
          - types-PyYAML
          - types-requests
        exclude: ^(tests/|docs/)

  # Security linting
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/, -f, txt]
        exclude: tests/

  # Documentation
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=numpy, --add-ignore=D100,D104]
        exclude: ^(tests/|setup.py)

  # YAML linting for model files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1  
    hooks:
      - id: yamllint
        args: [-d, relaxed]
        files: \.ya?ml$

  # Check for common issues in Python code
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # Check for common security issues
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]

# Configuration for specific hooks
default_language_version:
  python: python3.11

# Files to exclude from all hooks
exclude: |
  (?x)^(
    docs/_build/|
    .git/|
    .venv/|
    venv/|
    __pycache__/|
    .*\.egg-info/|
    dist/|
    build/
  )$

# Minimum pre-commit version
minimum_pre_commit_version: "3.0.0"
